spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl: true
      ddl-auto: create
    properties:
  datasource:
    url: jdbc:mysql://localhost:3306/account_service_databaseuse?useSSL=false

    username: root
    password: kali
#    driver-class-name: com.mysql.jdbc.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081
