spring:
  jpa:
    database: MYSQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/bill_service_databaseuse?useSSL=false

    username: root
    password: kali
    driver-class-name: com.mysql.jdbc.Driver

server:
  servlet:
    context-path: /bills
  port: 8082
