spring:
  jpa:
    database: MYSQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/deposit_service_databaseuse?useSSL=false

    username: root
    password: kali
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true
